spring:
  datasource:
    url: jdbc:mysql://www.deschen.cn:3306/my_blog?characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  redis:
#    host: www.deschen.cn
    host: localhost
    port: 6379
#    password: root123
server:
#  port: 80
  servlet:
    context-path: /myblog
idworker:
  workerId: 1
  datacenterId: 1
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  mybatis.config-location: classpath:/mybatis-config.xml
  mybatis.type-aliases-package: com.deschen.myblog.modules.system.entity
# pageHelper\u63D2\u4EF6\u914D\u7F6E
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#  page-size-zero: true  // 当设置为true的时候，如果pagesize设置为0（或RowBounds的limit=0），就不执行分页，返回全部结果
com:
  deschen:
    myblog:
      dir: E:/ideaProjects/myblog/
