spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
  redis:
    host: www.deschen.cn
    port: 6379
    password: root123
server:
  port: 80
  servlet:
    context-path: /myblog
idworker:
  workerId: 1
  datacenterId: 1
