spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  redis:
#    host: www.deschen.cn
    host: localhost
    port: 6379
#    password: root123
server:
#  port: 80
  servlet:
    context-path: /myblog
idworker:
  workerId: 1
  datacenterId: 1
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  mybatis.config-location: classpath:/mybatis-config.xml
  mybatis.type-aliases-package: com.deschen.myblog.modules.system.entity
# pageHelper\u63D2\u4EF6\u914D\u7F6E
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true
com:
  deschen:
    myblog:
      dir: E:/ideaProjects/myblog/
